# Generated by Django 4.1.4 on 2022-12-19 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeUp',
            fields=[
                ('code_up', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='상위코드')),
                ('code_up_name', models.CharField(max_length=100, verbose_name='상위코드 명')),
                ('code_up_info', models.TextField(null=True, verbose_name='상위코드 설명')),
                ('code_up_status', models.CharField(default='show', max_length=10, verbose_name='상위코드 상태')),
                ('insert_id', models.CharField(max_length=100, null=True, verbose_name='insert id')),
                ('insert_date', models.DateTimeField(null=True, verbose_name='insert date')),
                ('update_id', models.CharField(max_length=100, null=True, verbose_name='update id')),
                ('update_date', models.DateTimeField(null=True, verbose_name='update date')),
            ],
            options={
                'verbose_name': 'Code Up',
                'verbose_name_plural': 'Code Up',
                'ordering': ['-code_up'],
            },
        ),
        migrations.CreateModel(
            name='CodeDown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_down', models.BigIntegerField(verbose_name='하위코드')),
                ('code_value1', models.CharField(max_length=500, verbose_name='값1')),
                ('code_value2', models.CharField(max_length=500, verbose_name='값1')),
                ('code_value3', models.CharField(max_length=500, verbose_name='값1')),
                ('code_value4', models.CharField(max_length=500, verbose_name='값1')),
                ('code_value5', models.CharField(max_length=500, verbose_name='값1')),
                ('code_down_status', models.CharField(default='show', max_length=10, verbose_name='하위코드 상태')),
                ('insert_id', models.CharField(max_length=100, null=True, verbose_name='insert id')),
                ('insert_date', models.DateTimeField(null=True, verbose_name='insert date')),
                ('update_id', models.CharField(max_length=100, null=True, verbose_name='update id')),
                ('update_date', models.DateTimeField(null=True, verbose_name='update date')),
                ('code_up_code', models.ForeignKey(db_column='code_up_code', on_delete=django.db.models.deletion.CASCADE, related_name='상위코드', to='dev.codeup')),
            ],
            options={
                'verbose_name': 'Code down',
                'verbose_name_plural': 'Code down',
            },
        ),
        migrations.AddConstraint(
            model_name='codedown',
            constraint=models.UniqueConstraint(fields=('code_up_code', 'code_down'), name='unique code_up_down'),
        ),
    ]
