# Generated by Django 4.1.4 on 2022-12-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='insert_date',
            field=models.DateTimeField(null=True, verbose_name='insert date'),
        ),
        migrations.AddField(
            model_name='user',
            name='insert_id',
            field=models.CharField(max_length=100, null=True, verbose_name='insert id'),
        ),
        migrations.AddField(
            model_name='user',
            name='update_date',
            field=models.DateTimeField(null=True, verbose_name='update date'),
        ),
        migrations.AddField(
            model_name='user',
            name='update_id',
            field=models.CharField(max_length=100, null=True, verbose_name='update id'),
        ),
    ]
