# Generated by Django 4.1.4 on 2022-12-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Egginfo",
            fields=[
                ("farm_code", models.BigIntegerField(verbose_name="농장코드")),
                ("barn_code", models.BigIntegerField(verbose_name="축사코드")),
                ("egg_code", models.BigAutoField(primary_key=True, serialize=False)),
                ("egg_registration_date", models.CharField(max_length=100)),
                ("egg_type", models.IntegerField()),
                ("egg_number", models.BigIntegerField()),
            ],
        ),
    ]
