# Generated by Django 4.1.4 on 2022-12-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Egginfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "farm_code",
                    models.CharField(max_length=50, null=True, verbose_name="농장 이름"),
                ),
                ("barn_code", models.CharField(max_length=50, verbose_name="축사 이름")),
                (
                    "egg_registration_date",
                    models.DateTimeField(verbose_name="egg_registration_date"),
                ),
                ("egg_type", models.CharField(max_length=50, verbose_name="egg_type")),
                ("egg_number", models.BigIntegerField(verbose_name="egg_number")),
            ],
        ),
    ]
