# Generated by Django 4.1.4 on 2022-12-30 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Farm_Management",
            fields=[
                (
                    "farm_code",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, verbose_name="농가코드"
                    ),
                ),
                ("farm_name", models.CharField(max_length=100, verbose_name="농가명")),
                (
                    "company_num",
                    models.CharField(max_length=100, null=True, verbose_name="사업자번호"),
                ),
                (
                    "farm_owner",
                    models.CharField(max_length=50, null=True, verbose_name="대표자명"),
                ),
                (
                    "farm_postcode",
                    models.CharField(max_length=20, null=True, verbose_name="우편번호"),
                ),
                (
                    "farm_addr1",
                    models.CharField(max_length=500, null=True, verbose_name="주소"),
                ),
                (
                    "farm_addr2",
                    models.CharField(max_length=500, null=True, verbose_name="상세주소"),
                ),
                (
                    "farm_tel_num",
                    models.CharField(max_length=100, null=True, verbose_name="연락처"),
                ),
                ("farm_status", models.CharField(max_length=10, verbose_name="농가상태")),
                (
                    "insert_id",
                    models.CharField(
                        max_length=100, null=True, verbose_name="insert id"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Barn_Management",
            fields=[
                (
                    "barn_code",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, verbose_name="축사코드"
                    ),
                ),
                ("barn_name", models.CharField(max_length=50, verbose_name="축사이름")),
                (
                    "barn_info_scale",
                    models.CharField(max_length=50, verbose_name="축사규모"),
                ),
                (
                    "barn_info_volumn",
                    models.CharField(max_length=50, verbose_name="축사용량"),
                ),
                (
                    "barn_info_bigo",
                    models.CharField(max_length=50, verbose_name="축사설명"),
                ),
                (
                    "farm_code",
                    models.ForeignKey(
                        db_column="farm_code",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="농가코드",
                        to="farm_management.farm_management",
                    ),
                ),
            ],
            options={
                "verbose_name": "Barn manage",
                "verbose_name_plural": "Barn manage",
            },
        ),
        migrations.AddConstraint(
            model_name="barn_management",
            constraint=models.UniqueConstraint(
                fields=("farm_code", "barn_code"), name="unique farm_and_barn"
            ),
        ),
    ]
