# Generated by Django 4.1.4 on 2022-12-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Barn_Managemnet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barn_name", models.CharField(max_length=50, verbose_name="축사이름")),
                (
                    "barn_info_scale",
                    models.CharField(max_length=50, verbose_name="축사규모"),
                ),
                (
                    "barn_info_volumn",
                    models.CharField(max_length=50, verbose_name="축사용량"),
                ),
                (
                    "barn_info_bigo",
                    models.CharField(max_length=50, verbose_name="축사설명"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Farm_Management",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("farm_name", models.CharField(max_length=100, verbose_name="농가명")),
                (
                    "company_num",
                    models.CharField(max_length=100, null=True, verbose_name="사업자번호"),
                ),
                (
                    "farm_owner",
                    models.CharField(max_length=50, null=True, verbose_name="대표자명"),
                ),
                (
                    "farm_postcode",
                    models.CharField(max_length=20, null=True, verbose_name="우편번호"),
                ),
                (
                    "farm_addr1",
                    models.CharField(max_length=500, null=True, verbose_name="주소"),
                ),
                (
                    "farm_addr2",
                    models.CharField(max_length=500, null=True, verbose_name="상세주소"),
                ),
                (
                    "farm_tel_num",
                    models.CharField(max_length=100, null=True, verbose_name="연락처"),
                ),
                ("farm_status", models.CharField(max_length=10, verbose_name="농가상태")),
            ],
        ),
    ]
