# Generated by Django 4.1.4 on 2023-01-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_Farm",
            fields=[
                (
                    "id_farm",
                    models.BigIntegerField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id_farm",
                    ),
                ),
                (
                    "insert_id",
                    models.CharField(max_length=100, verbose_name="insert id"),
                ),
                ("insert_farm", models.BigIntegerField(verbose_name="insert_farm")),
            ],
        ),
        migrations.RemoveField(
            model_name="barn_management",
            name="barn_in_farm",
        ),
    ]
