# Generated by Django 4.1 on 2023-01-03 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('farm_code', models.CharField(max_length=500, primary_key=True, serialize=False, verbose_name='농가코드')),
                ('farm_name', models.CharField(max_length=100, verbose_name='농가명')),
                ('company_num', models.CharField(max_length=100, null=True, verbose_name='사업자번호')),
                ('farm_owner', models.CharField(max_length=50, null=True, verbose_name='대표자명')),
                ('farm_postcode', models.CharField(max_length=20, null=True, verbose_name='우편번호')),
                ('farm_addr1', models.CharField(max_length=500, null=True, verbose_name='주소')),
                ('farm_addr2', models.CharField(max_length=500, null=True, verbose_name='상세주소')),
                ('farm_tel_num', models.CharField(max_length=100, null=True, verbose_name='연락처')),
                ('farm_status', models.CharField(max_length=10, verbose_name='농가상태')),
                ('insert_id', models.CharField(max_length=100, null=True, verbose_name='insert id')),
                ('insert_date', models.DateTimeField(null=True, verbose_name='insert date')),
                ('update_id', models.CharField(max_length=100, null=True, verbose_name='update id')),
                ('update_date', models.DateTimeField(null=True, verbose_name='update date')),
            ],
            options={
                'ordering': ['insert_date'],
            },
        ),
        migrations.CreateModel(
            name='User_Farm',
            fields=[
                ('user_farm_idx', models.BigAutoField(primary_key=True, serialize=False)),
                ('farm_farm_code', models.ForeignKey(db_column='farm_farm_code', on_delete=django.db.models.deletion.CASCADE, related_name='uf_농가코드', to='farms.farm')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='유저고유값', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Barn',
            fields=[
                ('barn_code', models.BigAutoField(primary_key=True, serialize=False, verbose_name='축사코드')),
                ('barn_name', models.CharField(max_length=100, verbose_name='축사이름')),
                ('barn_info_scale', models.CharField(max_length=50, null=True, verbose_name='축사규모')),
                ('barn_info_volumn', models.CharField(max_length=50, null=True, verbose_name='축사용량')),
                ('barn_info_bigo', models.CharField(max_length=50, null=True, verbose_name='축사설명')),
                ('insert_id', models.CharField(max_length=100, null=True, verbose_name='insert id')),
                ('insert_date', models.DateTimeField(null=True, verbose_name='insert date')),
                ('update_id', models.CharField(max_length=100, null=True, verbose_name='update id')),
                ('update_date', models.DateTimeField(null=True, verbose_name='update date')),
                ('farm_farm_code', models.ForeignKey(db_column='farm_farm_code', on_delete=django.db.models.deletion.CASCADE, related_name='농가코드', to='farms.farm')),
            ],
        ),
    ]
